### ISSUE TITLE
Coarse registration did not work

### ISSUE THREAD

**Issue by sunshine2004** [JunkangZhang/RetinalSegReg#1]
Seems the file FFAPCFIDP_affine.csv is not a correct one. The 1st row is the transformed pair.
![image](https://user-images.githubusercontent.com/51089312/94984287-66097700-04ff-11eb-98c9-27cc1558a850.png)

**Comment by sunshine2004** [comment]
Seems it works now if I comment either line #79 or line #85 in file of utils_image.py. Please check with that

**Comment by JunkangZhang** [comment]
> Seems the file FFAPCFIDP_affine.csv is not a correct one. The 1st row is the transformed pair.
> ![image](https://user-images.githubusercontent.com/51089312/94984287-66097700-04ff-11eb-98c9-27cc1558a850.png)

The images look correct. 
The upper-left image (src_t) is to be matched with the lower-right one (tgt).  And upper-right (tgt_t) and lower-left (src) ones form another pair.

**Comment by sunshine2004** [comment]
Thanks. Yes, the file is correct. My understanding was poor. 
There is a new problem when I tried to run train_step2.py：
checkpoint: ckpt/icip_train/ckpt_500.pth.tar
network parameters loaded 
training state loaded 
/home/jia/anaconda2/envs/Cuda_15/lib/python3.5/site-packages/torch/nn/functional.py:2705: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
/home/jia/anaconda2/envs/Cuda_15/lib/python3.5/site-packages/torch/nn/functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "/data/jia/Networks/Fundus/RetinalSegReg/train_step2.py", line 47, in <module>
    model.Train()
  File "/data/jia/Networks/Fundus/RetinalSegReg/RetSegReg.py", line 348, in Train
    self.optimizer.step()
  File "/home/jia/anaconda2/envs/Cuda_15/lib/python3.5/site-packages/torch/optim/adam.py", line 95, in step
    exp_avg.mul_(beta1).add_(1 - beta1, grad)
RuntimeError: The size of tensor a (128) must match the size of tensor b (64) at non-singleton dimension 1

Process finished with exit code 1

**Comment by sunshine2004** [comment]
Thanks! My understanding was poor and the file is correct
